services:
  - type: worker
    name: sovereign
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DERIV_APP_ID
        sync: false
      - key: DERIV_API_TOKEN
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID_1
        sync: false
      - key: TELEGRAM_CHAT_ID_2
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false